
version: '3.8'

services:
  certifydpro-web:
    image: nginx:alpine
    container_name: certifydpro-web
    restart: unless-stopped
    ports:
      - "9001:80"
    volumes:
      - certifydpro_html:/usr/share/nginx/html:ro
      - certifydpro_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    environment:
      - TZ=America/New_York
    depends_on:
      - git-sync
    networks:
      - certifydpro-net

  certifydpro-filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: certifydpro-filebrowser
    restart: unless-stopped
    ports:
      - "9002:80"
    volumes:
      - certifydpro_html:/srv:ro
      - git_repo:/git:ro
      - filebrowser_db:/database
    environment:
      - FB_BASEURL=/
      - FB_NOAUTH=false
    networks:
      - certifydpro-net

  git-sync:
    image: node:18-alpine
    container_name: certifydpro-git-sync
    restart: unless-stopped
    volumes:
      - certifydpro_html:/webroot
      - git_repo:/repo
      - node_modules_cache:/repo/node_modules
    environment:
      - GIT_REPO=https://github.com/SkyNet-90/certifyd-website.git
      - GIT_BRANCH=main
      - SYNC_INTERVAL=300
      - NODE_ENV=production
    command: >
      sh -c '
        echo "🚀 Starting CertifydPro git-sync with build capability...";
        apk add --no-cache git curl;
        cd /repo;
        if [ ! -d ".git" ]; then
          echo "🧹 Cleaning up existing non-git content...";
          rm -rf /repo/*;
          rm -rf /repo/.*;
        fi;
        if [ -d ".git" ]; then
          echo "📦 Git repository exists, resetting and pulling...";
          git reset --hard HEAD || echo "Reset failed";
          git clean -fd || echo "Clean failed";
          git pull origin main || echo "Pull failed, will retry";
        else
          echo "📥 Cloning repository...";
          git clone https://github.com/SkyNet-90/certifyd-website.git /tmp/repo-clone || exit 1;
          cp -r /tmp/repo-clone/* /repo/;
          cp -r /tmp/repo-clone/.git /repo/;
          rm -rf /tmp/repo-clone;
          cd /repo;
          git checkout main || echo "Branch checkout failed";
        fi;
        if [ ! -f "package.json" ]; then
          echo "❌ Error: package.json not found in repository";
          exit 1;
        fi;
        echo "🔨 Installing dependencies and building...";
        npm ci --production=false || exit 1;
        npm run build || exit 1;
        echo "📋 Copying built files to web directory...";
        rm -rf /webroot/*;
        cp -r dist/* /webroot/ || exit 1;
        echo "✅ Initial deployment completed. Starting periodic sync...";
        while true; do
          sleep 300;
          echo "🔄 Checking for updates at $(date)";
          cd /repo;
          BEFORE=$(git rev-parse HEAD 2>/dev/null || echo "unknown");
          echo "📋 Current commit: $BEFORE";
          git reset --hard HEAD || echo "Reset failed";
          git clean -fd || echo "Clean failed";
          git pull origin main || (echo "Git pull failed, retrying in next cycle" && continue);
          AFTER=$(git rev-parse HEAD 2>/dev/null || echo "unknown");
          echo "📋 After pull commit: $AFTER";
          if [ "$BEFORE" != "$AFTER" ]; then
            echo "📦 Changes detected! Old: $BEFORE -> New: $AFTER";
            echo "🔨 Rebuilding project...";
            npm ci --production=false || (echo "npm ci failed" && continue);
            npm run build || (echo "Build failed" && continue);
            echo "🚀 Deploying new build...";
            rm -rf /webroot/*;
            cp -r dist/* /webroot/ || (echo "Copy failed" && continue);
            echo "✅ Deployment completed successfully!";
          else
            echo "ℹ️  No changes detected (commit: $AFTER)";
          fi;
        done
      '
    networks:
      - certifydpro-net
    healthcheck:
      test: ["CMD", "test", "-f", "/webroot/index.html"]
      interval: 60s
      timeout: 10s
      retries: 3

  cloudflared-certifydpro:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-certifydpro
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CF_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    depends_on:
      - certifydpro-web
    networks:
      - certifydpro-net

volumes:
  certifydpro_html:
    driver: local
  certifydpro_logs:
    driver: local
  git_repo:
    driver: local
  node_modules_cache:
    driver: local
  filebrowser_db:
    driver: local

networks:
  certifydpro-net:
    driver: bridge
